import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
import os

# Set plot style for premium aesthetics
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("viridis")

def load_data(filepath):
    """Loads the dataset and parses dates."""
    print(f"Loading data from {filepath}...")
    df = pd.read_csv(filepath)
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date').reset_index(drop=True)
    return df

def generate_eda(df, output_dir):
    """Generates 3 EDA plots focusing on Copper vs USD/PEN."""
    print("Generating EDA plots...")
    os.makedirs(output_dir, exist_ok=True)
    
    # Plot 1: Time Series Comparison
    fig, ax1 = plt.subplots(figsize=(12, 6))
    
    color = 'tab:blue'
    ax1.set_xlabel('Date')
    ax1.set_ylabel('USD/PEN (TC_Yahoo)', color=color)
    ax1.plot(df['Date'], df['TC_Yahoo'], color=color, label='USD/PEN')
    ax1.tick_params(axis='y', labelcolor=color)
    
    ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis
    color = 'tab:orange'
    ax2.set_ylabel('Copper Futures', color=color)  # we already handled the x-label with ax1
    ax2.plot(df['Date'], df['Cobre_Futuros'], color=color, label='Copper')
    ax2.tick_params(axis='y', labelcolor=color)
    
    plt.title('Time Series: USD/PEN vs Copper Futures')
    fig.tight_layout()
    plt.savefig(os.path.join(output_dir, 'eda_timeseries_copper_fx.png'))
    plt.close()

    # Plot 2: Correlation Heatmap
    plt.figure(figsize=(10, 8))
    corr_cols = ['TC_Yahoo', 'Cobre_Futuros', 'DXY_IndiceDolar', 'VIX_Volatilidad', 'RIN_Reservas']
    corr_matrix = df[corr_cols].corr()
    sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
    plt.title('Correlation Matrix')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'eda_correlation_matrix.png'))
    plt.close()

    # Plot 3: Scatter Plot with Trendline
    plt.figure(figsize=(10, 6))
    sns.regplot(x='Cobre_Futuros', y='TC_Yahoo', data=df, scatter_kws={'alpha':0.5}, line_kws={'color':'red'})
    plt.title('Scatter Plot: Copper vs USD/PEN')
    plt.xlabel('Copper Futures')
    plt.ylabel('USD/PEN (TC_Yahoo)')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'eda_scatter_copper_fx.png'))
    plt.close()
    print(f"EDA plots saved to {output_dir}")

def feature_engineering(df):
    """Creates Log Returns, Volatility, and Spread."""
    print("Performing Feature Engineering...")
    df = df.copy()
    
    # Log Returns
    df['Log_Ret'] = np.log(df['TC_Yahoo'] / df['TC_Yahoo'].shift(1))
    
    # 10-day Volatility (Rolling Std Dev of Log Returns)
    df['Vol_10d'] = df['Log_Ret'].rolling(window=10).std()
    
    # Spread (TC_Yahoo - TC_Oficial_BCRP)
    df['Spread_TC'] = df['TC_Yahoo'] - df['TC_Oficial_BCRP']
    
    # Drop NaN values generated by shifting/rolling
    df = df.dropna().reset_index(drop=True)
    
    return df

def apply_scaling(df, feature_cols):
    """Applies StandardScaler to specified features."""
    print("Applying Scaling (StandardScaler)...")
    scaler = StandardScaler()
    df_scaled = df.copy()
    df_scaled[feature_cols] = scaler.fit_transform(df[feature_cols])
    return df_scaled, scaler

def apply_pca(df, pca_cols, n_components=3):
    """Applies PCA to reduce dimensionality of external variables."""
    print(f"Applying PCA to reduce {pca_cols} to {n_components} components...")
    pca = PCA(n_components=n_components)
    pca_features = pca.fit_transform(df[pca_cols])
    
    # Create new dataframe with PCA components
    pca_df = pd.DataFrame(data=pca_features, columns=[f'PCA_{i+1}' for i in range(n_components)])
    
    # Concatenate with original dataframe (minus the pca_cols if desired, but we keep them for reference or drop later)
    # For the model input, we'll use the PCA columns.
    df_final = pd.concat([df, pca_df], axis=1)
    
    print(f"Explained Variance Ratio: {pca.explained_variance_ratio_}")
    return df_final, pca

if __name__ == "__main__":
    # Configuration
    DATA_PATH = r"c:/Users/curay/Downloads/Analitica Final/Modelo Analitica/DATASET_GRUPO3_FINAL_DIC01.csv"
    OUTPUT_DIR = "output_images"
    
    # 1. Load Data
    df = load_data(DATA_PATH)
    
    # 2. EDA
    generate_eda(df, OUTPUT_DIR)
    
    # 3. Feature Engineering
    df_fe = feature_engineering(df)
    
    # 4. Scaling (We scale before PCA usually, or scale the inputs for PCA)
    # The prompt asks to apply scaling citing page 135-140. Usually standardization is key for PCA.
    # We will scale the external variables before PCA.
    external_vars = ['Cobre_Futuros', 'DXY_IndiceDolar', 'VIX_Volatilidad', 'RIN_Reservas']
    
    # Scale external vars specifically for PCA
    scaler_pca = StandardScaler()
    df_fe[external_vars] = scaler_pca.fit_transform(df_fe[external_vars])
    
    # 5. PCA
    df_pca, pca_model = apply_pca(df_fe, external_vars, n_components=3)
    
    # Save processed data
    df_pca.to_csv("processed_data.csv", index=False)
    print("Preprocessing complete. Data saved to 'processed_data.csv'.")
